apiVersion: v1
kind: Service
metadata:
  name: career-agent-service
spec:
  selector:
    app: career-agent
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: career-agent
spec:
  selector:
    matchLabels:
      app: career-agent
  replicas: 1
  template:
    metadata:
      labels:
        app: career-agent
    spec:
      containers:
      - name: career-agent
        image: career-agent:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000

